format = """
$os\
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill\
$cmd_duration\
$nodejs\
$bun\
$deno\
$docker_context\
$memory_usage\
$battery\
$shell\
$time\
$username\
$line_break\
$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'

[os]
format = '[ÓÇ∂](fg:red)[$symbol ](fg:primary bg:red)[ÓÇ¥](fg:red)'
disabled = false

[os.symbols]
Macos = 'Û∞ä†'
Linux = 'Û∞åΩ'
Ubuntu = 'Û∞ïà'
Debian = 'Û∞£ö'
Alpine = ''
Arch = 'Û∞£á'
CentOS = ''
Fedora = 'Û∞£õ'

[directory]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:pink)[Û∞âñ ](fg:primary bg:pink)[ÓÇ¥](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[ÓÇ¥](fg:box)'
home_symbol = " ~/"
truncation_symbol = ' '
truncation_length = 2
read_only = 'Û±ûµ '
read_only_style = ''

[git_branch]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:green)[Ôêò](fg:primary bg:green)[ÓÇ¥](fg:green bg:box)[ $branch](fg:foreground bg:box)'
symbol = 'Ôêò '

[git_status]
format = '[( $all_status$ahead_behind)](fg:foreground bg:box)[ÓÇ¥](fg:box)'
ahead = '‚á°${count}'
behind = '‚á£${count}'
diverged = '‚áï‚á°${ahead_count}‚á£${behind_count}'

[git_metrics]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:cyan)[Û∞ä§ ](fg:primary bg:cyan)[ÓÇ¥](fg:cyan bg:box)[ +$added/-$deleted](fg:foreground bg:box)[ÓÇ¥](fg:box)'
disabled = false

[nodejs]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:green)[Û∞£ô](fg:primary bg:green)[ÓÇ¥](fg:green bg:box)[ $version](fg:foreground bg:box)[ÓÇ¥](fg:box)'
detect_files = ["package.json", ".node-version", "!bunfig.toml", "!bun.lockb"]

[bun]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:green)[ü•ü](fg:primary bg:green)[ÓÇ¥](fg:green bg:box)[ $version](fg:foreground bg:box)[ÓÇ¥](fg:box)'

[deno]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:green)[ü¶ï](fg:primary bg:green)[ÓÇ¥](fg:green bg:box)[ $version](fg:foreground bg:box)[ÓÇ¥](fg:box)'

[docker_context]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:cyan)[Û∞°® ](fg:primary bg:cyan)[ÓÇ¥](fg:cyan bg:box)[ $context](fg:foreground bg:box)[ÓÇ¥](fg:box)'

[memory_usage]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:orange)[Û∞çõ ](fg:primary bg:orange)[ÓÇ¥](fg:orange bg:box)[ $ram](fg:foreground bg:box)[ÓÇ¥](fg:box)'
disabled = false
threshold = 0

[battery]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:green)[$symbol](fg:primary bg:green)[ÓÇ¥](fg:green bg:box)[ $percentage](fg:foreground bg:box)[ÓÇ¥](fg:box)'

[[battery.display]]
threshold = 100
style = 'fg:foreground bg:box'

[fill]
symbol = '‚îÄ'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:orange)[ÔÄî ](fg:primary bg:orange)[ÓÇ¥](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[ÓÇ¥](fg:box)'

[shell]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:blue)[ÔÑ† ](fg:primary bg:blue)[ÓÇ¥](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[ÓÇ¥](fg:box)'
disabled = false

[time]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:purple)[Û∞ô¶ ](fg:primary bg:purple)[ÓÇ¥](fg:purple bg:box)[ $time](fg:foreground bg:box)[ÓÇ¥](fg:box)'
time_format = '%H:%M'
disabled = false

[username]
format = '[‚îÄ](fg:current_line)[ÓÇ∂](fg:yellow)[ÔÄá ](fg:primary bg:yellow)[ÓÇ¥](fg:yellow bg:box)[ $user](fg:foreground bg:box)[ÓÇ¥](fg:box) '
show_always = true

[character]
format = '$symbol '
success_symbol = '[‚ùØ‚ùØ](fg:bold green)'
error_symbol = '[‚ùØ‚ùØ](fg:bold red)'
