git:
  branchLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --"
  pagers:
    - pager: delta --dark --paging=never --side-by-side --line-numbers --syntax-theme="Visual Studio Dark+"
      colorArg: always
    - pager: delta --dark --paging=never --line-numbers --syntax-theme="Visual Studio Dark+"
      colorArg: always
  allBranchesLogCmds:
    - git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all
gui:
  sidePanelWidth: 0.15
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
    showIcons: true
    nerdFontsVersion: "3"
refresher:
  refreshInterval: 3
os:
  editCommand: "nvim"
